### ISSUE TITLE
一些不支持的测试用例

### ISSUE THREAD

**Issue by vuhe** [magiclen/chinese-number#5]
有两个确定的问题：

1. 直接转换繁体 `兩千` 可以得到正确的结果，对应的一个简体 `两千` 会出现解析错误
2. 古语中常用 `廿` 表示 20，在农历日历表示 20 时常用，直接解析会出现解析错误

还有一个不确定的问题：

口语中常用 `三万五` 表示 `三万五千` 即 `3_5000` ，解析结果为 `30005` 我不确定这个用例是否有歧义

其他的类似 `两千六` 表示 `2600`、 `一百二` 表示 `120`

**Comment by magiclen** [comment]
感謝您的回報。

1. 0.7.5 新版本已添加對 `两` 的解析支援。
2. `廿`、`卅`、`卌` 等字目前不考慮支援。如果有農曆解析需求可以參考我的另一個 crate [`chinese-lunisolar-calendar`](https://crates.io/crates/chinese-lunisolar-calendar)
3. 我覺得您提到的 「`三万五` 表示 `三万五千` 即 `3_5000`」我也覺得確實應該要如此，所以新版也改成這樣了。
